theme: jekyll-theme-cayman

title: [Computational Tonal Studies]
description: [This is the website of the Computational Tonal Studies (CTS) group. CTS is a community of students and postdoc(s) led by Prof. Ichiro Fujinaga, which are interested in the computational study of tonal music.]